version: "2"
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: im-redis-compose
        restart: always
        command: redis-server --appendonly yes
        networks:
            - app-network
    
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        container_name: im-rabbitmq-compose
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: my_vhost
        networks:
            - app-network

    backend:
        build: .
        links:
            - "redis"
            - "rabbitmq"
        container_name: im-server-compose
        depends_on:
            - rabbitmq
            - redis
        ports:
            - "3000:3000"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge